@extends('layouts.admin')

@section('title', 'Admin Dashboard - Savora Cafeteria')

@section('admin_content')
    <section class="admin-page-heading" id="dashboard"><div><span class="admin-eyebrow">Operations overview</span><h1>Welcome back, <span id="headingAdminName">Admin</span>.</h1><p>Here’s what’s happening with your cafeteria today.</p></div><a class="admin-primary-button" href="{{ route('admin.ai') }}"><i class="bi bi-stars"></i> Ask AI</a></section>
    <div id="adminNotice" class="admin-notice" role="status"></div>
    <section class="admin-stat-grid"><article class="admin-stat-card"><span class="admin-stat-icon green"><i class="bi bi-people"></i></span><div><small>Customers</small><strong data-stat="customers_count">--</strong><em data-stat-sub="new_customers_7d">--</em></div></article><article class="admin-stat-card"><span class="admin-stat-icon amber"><i class="bi bi-bag-check"></i></span><div><small>Orders</small><strong data-stat="orders_count">--</strong><em data-stat-sub="orders_today">--</em></div></article><article class="admin-stat-card"><span class="admin-stat-icon terracotta"><i class="bi bi-cash-stack"></i></span><div><small>Revenue</small><strong data-stat="sales_total">--</strong><em data-stat-sub="sales_today">--</em></div></article><article class="admin-stat-card"><span class="admin-stat-icon olive"><i class="bi bi-box-seam"></i></span><div><small>Catalog stock</small><strong data-stat="available_products">--</strong><em data-stat-sub="low_stock_count">--</em></div></article></section>
    <section class="admin-dashboard-grid"><article class="admin-panel admin-panel-wide"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Performance</span><h2>Sales overview</h2></div><span class="admin-panel-meta">Last 14 days</span></div><div id="salesChart" class="admin-sales-chart"><div class="admin-loading">Loading sales data...</div></div></article><article class="admin-panel"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Fulfillment</span><h2>Order status</h2></div></div><div id="statusChart" class="admin-status-list"><div class="admin-loading">Loading status data...</div></div></article><article class="admin-panel"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Top sellers</span><h2>Popular items</h2></div></div><div id="popularItems" class="admin-mini-list"><div class="admin-loading">Loading popular items...</div></div></article><article class="admin-panel admin-panel-wide"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Latest activity</span><h2>Recent orders</h2></div><a href="{{ route('admin.orders') }}" class="admin-text-link">View all</a></div><div id="recentOrders" class="admin-recent-list"><div class="admin-loading">Loading orders...</div></div></article><article class="admin-panel"><div class="admin-panel-heading"><div><span class="admin-eyebrow">Inventory attention</span><h2>Low stock</h2></div><a href="{{ route('admin.food-items') }}" class="admin-text-link">Manage</a></div><div id="lowStockItems" class="admin-mini-list"><div class="admin-loading">Loading inventory...</div></div></article></section>
@endsection
